version: "3.9"

services:
  soap:
    image: tomhoffer/aass-api-server-soap
    command: npm run start:soap
    ports:
      - "8000:8000"

  order:
    image: tomhoffer/aass-order-service
    command: npm run start
    ports:
      - "3002:3002"

  item:
    image: tomhoffer/aass-item-service
    command: npm run start
    ports:
      - "3001:3001"

  login:
    image: tomhoffer/aass-login-service
    command: npm run start
    ports:
      - "3003:3003"

  api-gateway:
    image: tomhoffer/aass-api-gateway
    command: bash -c "/usr/bin/nginx -g 'daemon off;'"
    ports:
      - 8081:8081

